### ISSUE TITLE
Testing Learned Index in C++ code

### ISSUE THREAD

**Issue by quito418** [mkirsche/sapling#3]
Hi,

I like to test speed of learned index in c++ code

It seems current align.cc or sapling_example.cc have only piecewise linear query implemented.

Is there implementation for loading learned index model and querying with learned index?

Thank you

**Comment by mkirsche** [comment]
Hi,

The intended learned index to use with Sapling is the piecewise linear data model.  However, if you would like to use the neural network model for predicting suffix array positions, a guide for training and running that predictor can be found in the NN submodule of this repository: https://github.com/mkirsche/sapling/tree/master/NN

I hope that answers your question!
Melanie

**Comment by quito418** [comment]
Have you tried implemented loading neural network model in C++ code to compare runtime?

Also, I am curious if there is  any overhead other than required memory size when increasing buckets. If speed is important for me, can bucket search time matter?

Thank you for response

**Comment by mkirsche** [comment]
No, we haven't.  The query time is significantly higher than the piecewise linear model, so for comparing to other methods as a proof-of-concept. we thought that the piecewise linear prediction scheme would make a stronger case.  A more detailed explanation can be found in our paper.

As for the number of buckets, increasing the number of buckets results in higher memory usage, but serves to decrease runtime because it enables more accurate predictions of suffix array locations.

**Comment by quito418** [comment]
Thank you!
